# general
seed: 42
workers: 2
# dataset_dir: "~/datasets"
dataset_dir: "/kaggle/input/datasets/liusha249/imagenet10/imagenet-10"

# train options
batch_size: 64
image_size: 224
start_epoch: 0
epochs: 100
dataset: "ImageNet-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# model options
resnet: "ResNet18" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/ImageNet-10"
reload: False

# loss options
sigma: 1 # CIFAR-100: 0.5, other: 1
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
